// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bobsknobshop/peddler/v1/peddler.proto

package peddler

import (
	fmt "fmt"
	v1 "github.com/HayoVanLoon/genproto/bobsknobshop/common/v1"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchOrdersRequest struct {
	Customer             []string `protobuf:"bytes,1,rep,name=customer,proto3" json:"customer,omitempty"`
	ProductId            []string `protobuf:"bytes,2,rep,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchOrdersRequest) Reset()         { *m = SearchOrdersRequest{} }
func (m *SearchOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*SearchOrdersRequest) ProtoMessage()    {}
func (*SearchOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1afc1b6de397668, []int{0}
}

func (m *SearchOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchOrdersRequest.Unmarshal(m, b)
}
func (m *SearchOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchOrdersRequest.Marshal(b, m, deterministic)
}
func (m *SearchOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchOrdersRequest.Merge(m, src)
}
func (m *SearchOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_SearchOrdersRequest.Size(m)
}
func (m *SearchOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchOrdersRequest proto.InternalMessageInfo

func (m *SearchOrdersRequest) GetCustomer() []string {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *SearchOrdersRequest) GetProductId() []string {
	if m != nil {
		return m.ProductId
	}
	return nil
}

type SearchOrdersResponse struct {
	Orders               []*v1.Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SearchOrdersResponse) Reset()         { *m = SearchOrdersResponse{} }
func (m *SearchOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*SearchOrdersResponse) ProtoMessage()    {}
func (*SearchOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1afc1b6de397668, []int{1}
}

func (m *SearchOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchOrdersResponse.Unmarshal(m, b)
}
func (m *SearchOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchOrdersResponse.Marshal(b, m, deterministic)
}
func (m *SearchOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchOrdersResponse.Merge(m, src)
}
func (m *SearchOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_SearchOrdersResponse.Size(m)
}
func (m *SearchOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchOrdersResponse proto.InternalMessageInfo

func (m *SearchOrdersResponse) GetOrders() []*v1.Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchOrdersRequest)(nil), "bobsknobshop.peddler.v1.SearchOrdersRequest")
	proto.RegisterType((*SearchOrdersResponse)(nil), "bobsknobshop.peddler.v1.SearchOrdersResponse")
}

func init() {
	proto.RegisterFile("bobsknobshop/peddler/v1/peddler.proto", fileDescriptor_d1afc1b6de397668)
}

var fileDescriptor_d1afc1b6de397668 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xc1, 0x4a, 0xc4, 0x30,
	0x14, 0x74, 0x15, 0x56, 0x37, 0x7a, 0x8a, 0x82, 0x4b, 0x71, 0x41, 0x2a, 0x82, 0x07, 0x4d, 0xe8,
	0x8a, 0x27, 0x0f, 0x82, 0x27, 0x05, 0xc5, 0xa5, 0x82, 0x07, 0x2f, 0x4b, 0xda, 0x3c, 0xda, 0x62,
	0x9b, 0x17, 0x93, 0xb4, 0xe8, 0xdf, 0xcb, 0xa6, 0x5d, 0xd9, 0x82, 0x05, 0x6f, 0x93, 0xf7, 0x66,
	0x86, 0x99, 0x17, 0x72, 0x9e, 0x60, 0x62, 0x3f, 0x14, 0x26, 0x36, 0x47, 0xcd, 0x35, 0x48, 0x59,
	0x82, 0xe1, 0x4d, 0xb4, 0x86, 0x4c, 0x1b, 0x74, 0x48, 0x8f, 0x37, 0x69, 0x6c, 0xbd, 0x6b, 0xa2,
	0xe0, 0x24, 0x43, 0xcc, 0x4a, 0xe0, 0x42, 0x17, 0x5c, 0x28, 0x85, 0x4e, 0xb8, 0x02, 0x95, 0x6d,
	0x65, 0xc1, 0x59, 0xcf, 0x3d, 0xc5, 0xaa, 0x42, 0xb5, 0x32, 0x6f, 0x51, 0x4b, 0x0a, 0x17, 0xe4,
	0xf0, 0x15, 0x84, 0x49, 0xf3, 0x17, 0x23, 0xc1, 0xd8, 0x18, 0x3e, 0x6b, 0xb0, 0x8e, 0x06, 0x64,
	0x2f, 0xad, 0xad, 0xc3, 0x0a, 0xcc, 0x74, 0x74, 0xba, 0x73, 0x31, 0x89, 0x7f, 0xdf, 0x74, 0x46,
	0x88, 0x36, 0x28, 0xeb, 0xd4, 0x2d, 0x0b, 0x39, 0xdd, 0xf6, 0xdb, 0x49, 0x37, 0x79, 0x94, 0xe1,
	0x33, 0x39, 0xea, 0x3b, 0x5a, 0x8d, 0xca, 0x02, 0xbd, 0x21, 0x63, 0xf4, 0x13, 0x6f, 0xb8, 0x3f,
	0x9f, 0xb1, 0x5e, 0xad, 0x2e, 0x55, 0x13, 0x31, 0xaf, 0x8b, 0x3b, 0xf2, 0xfc, 0x8b, 0xec, 0x76,
	0x8d, 0x69, 0x45, 0x0e, 0x36, 0x9d, 0xe9, 0x25, 0x1b, 0x38, 0x0c, 0xfb, 0xa3, 0x52, 0x70, 0xf5,
	0x4f, 0x76, 0x1b, 0x37, 0xdc, 0xba, 0x5f, 0x92, 0x20, 0x2b, 0x87, 0x44, 0x8b, 0xd1, 0xfb, 0x5d,
	0x56, 0xb8, 0xbc, 0x4e, 0x56, 0xc9, 0xf9, 0x83, 0xf8, 0xc6, 0x37, 0xa1, 0x9e, 0x10, 0x15, 0xcf,
	0x40, 0xf9, 0xdb, 0xf2, 0x81, 0xdf, 0xbd, 0xed, 0x60, 0x32, 0xf6, 0xb4, 0xeb, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xb6, 0xab, 0xd3, 0xfa, 0x07, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PeddlerClient is the client API for Peddler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PeddlerClient interface {
	// Returns a classification for a comment
	SearchOrders(ctx context.Context, in *SearchOrdersRequest, opts ...grpc.CallOption) (*SearchOrdersResponse, error)
}

type peddlerClient struct {
	cc *grpc.ClientConn
}

func NewPeddlerClient(cc *grpc.ClientConn) PeddlerClient {
	return &peddlerClient{cc}
}

func (c *peddlerClient) SearchOrders(ctx context.Context, in *SearchOrdersRequest, opts ...grpc.CallOption) (*SearchOrdersResponse, error) {
	out := new(SearchOrdersResponse)
	err := c.cc.Invoke(ctx, "/bobsknobshop.peddler.v1.peddler/SearchOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeddlerServer is the server API for Peddler service.
type PeddlerServer interface {
	// Returns a classification for a comment
	SearchOrders(context.Context, *SearchOrdersRequest) (*SearchOrdersResponse, error)
}

func RegisterPeddlerServer(s *grpc.Server, srv PeddlerServer) {
	s.RegisterService(&_Peddler_serviceDesc, srv)
}

func _Peddler_SearchOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeddlerServer).SearchOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.peddler.v1.peddler/SearchOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeddlerServer).SearchOrders(ctx, req.(*SearchOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Peddler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bobsknobshop.peddler.v1.peddler",
	HandlerType: (*PeddlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchOrders",
			Handler:    _Peddler_SearchOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bobsknobshop/peddler/v1/peddler.proto",
}
