// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bobsknobshop/truth/v1/truth.proto

package truth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetServiceKpiRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	StartTimestamp       int64    `protobuf:"varint,2,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp         int64    `protobuf:"varint,3,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServiceKpiRequest) Reset()         { *m = GetServiceKpiRequest{} }
func (m *GetServiceKpiRequest) String() string { return proto.CompactTextString(m) }
func (*GetServiceKpiRequest) ProtoMessage()    {}
func (*GetServiceKpiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ed36ddfdb54d891, []int{0}
}

func (m *GetServiceKpiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceKpiRequest.Unmarshal(m, b)
}
func (m *GetServiceKpiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceKpiRequest.Marshal(b, m, deterministic)
}
func (m *GetServiceKpiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceKpiRequest.Merge(m, src)
}
func (m *GetServiceKpiRequest) XXX_Size() int {
	return xxx_messageInfo_GetServiceKpiRequest.Size(m)
}
func (m *GetServiceKpiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceKpiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceKpiRequest proto.InternalMessageInfo

func (m *GetServiceKpiRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *GetServiceKpiRequest) GetStartTimestamp() int64 {
	if m != nil {
		return m.StartTimestamp
	}
	return 0
}

func (m *GetServiceKpiRequest) GetEndTimestamp() int64 {
	if m != nil {
		return m.EndTimestamp
	}
	return 0
}

type GetServiceKpiResponse struct {
	Versions             []*GetServiceKpiResponse_Version `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *GetServiceKpiResponse) Reset()         { *m = GetServiceKpiResponse{} }
func (m *GetServiceKpiResponse) String() string { return proto.CompactTextString(m) }
func (*GetServiceKpiResponse) ProtoMessage()    {}
func (*GetServiceKpiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ed36ddfdb54d891, []int{1}
}

func (m *GetServiceKpiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceKpiResponse.Unmarshal(m, b)
}
func (m *GetServiceKpiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceKpiResponse.Marshal(b, m, deterministic)
}
func (m *GetServiceKpiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceKpiResponse.Merge(m, src)
}
func (m *GetServiceKpiResponse) XXX_Size() int {
	return xxx_messageInfo_GetServiceKpiResponse.Size(m)
}
func (m *GetServiceKpiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceKpiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceKpiResponse proto.InternalMessageInfo

func (m *GetServiceKpiResponse) GetVersions() []*GetServiceKpiResponse_Version {
	if m != nil {
		return m.Versions
	}
	return nil
}

type GetServiceKpiResponse_Version struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartTimestamp       int64    `protobuf:"varint,2,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp         int64    `protobuf:"varint,3,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	Unit                 string   `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	Value                float32  `protobuf:"fixed32,5,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServiceKpiResponse_Version) Reset()         { *m = GetServiceKpiResponse_Version{} }
func (m *GetServiceKpiResponse_Version) String() string { return proto.CompactTextString(m) }
func (*GetServiceKpiResponse_Version) ProtoMessage()    {}
func (*GetServiceKpiResponse_Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ed36ddfdb54d891, []int{1, 0}
}

func (m *GetServiceKpiResponse_Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceKpiResponse_Version.Unmarshal(m, b)
}
func (m *GetServiceKpiResponse_Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceKpiResponse_Version.Marshal(b, m, deterministic)
}
func (m *GetServiceKpiResponse_Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceKpiResponse_Version.Merge(m, src)
}
func (m *GetServiceKpiResponse_Version) XXX_Size() int {
	return xxx_messageInfo_GetServiceKpiResponse_Version.Size(m)
}
func (m *GetServiceKpiResponse_Version) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceKpiResponse_Version.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceKpiResponse_Version proto.InternalMessageInfo

func (m *GetServiceKpiResponse_Version) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetServiceKpiResponse_Version) GetStartTimestamp() int64 {
	if m != nil {
		return m.StartTimestamp
	}
	return 0
}

func (m *GetServiceKpiResponse_Version) GetEndTimestamp() int64 {
	if m != nil {
		return m.EndTimestamp
	}
	return 0
}

func (m *GetServiceKpiResponse_Version) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *GetServiceKpiResponse_Version) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*GetServiceKpiRequest)(nil), "bobsknobshop.truth.v1.GetServiceKpiRequest")
	proto.RegisterType((*GetServiceKpiResponse)(nil), "bobsknobshop.truth.v1.GetServiceKpiResponse")
	proto.RegisterType((*GetServiceKpiResponse_Version)(nil), "bobsknobshop.truth.v1.GetServiceKpiResponse.Version")
}

func init() { proto.RegisterFile("bobsknobshop/truth/v1/truth.proto", fileDescriptor_1ed36ddfdb54d891) }

var fileDescriptor_1ed36ddfdb54d891 = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4d, 0x4b, 0x2b, 0x31,
	0x14, 0x7d, 0xe9, 0xc7, 0xeb, 0x7b, 0xd1, 0x2a, 0x84, 0x16, 0x42, 0x71, 0x31, 0xd6, 0x85, 0x03,
	0xca, 0x84, 0x56, 0x77, 0xdd, 0xb9, 0x51, 0xd0, 0x45, 0x19, 0x4b, 0x41, 0x37, 0x92, 0x69, 0xc3,
	0x34, 0x38, 0x93, 0x3b, 0x4e, 0x32, 0x03, 0x6e, 0x04, 0x7f, 0x84, 0xff, 0x57, 0x26, 0xb1, 0xa5,
	0xca, 0x2c, 0x14, 0xdc, 0x9d, 0x7b, 0x72, 0x4e, 0xee, 0x3d, 0xc9, 0xc5, 0x87, 0x11, 0x44, 0xfa,
	0x51, 0x41, 0xa4, 0x57, 0x90, 0x31, 0x93, 0x17, 0x66, 0xc5, 0xca, 0x91, 0x03, 0x41, 0x96, 0x83,
	0x01, 0xd2, 0xdf, 0x96, 0x04, 0xee, 0xa4, 0x1c, 0x0d, 0x0e, 0x62, 0x80, 0x38, 0x11, 0x8c, 0x67,
	0x92, 0x71, 0xa5, 0xc0, 0x70, 0x23, 0x41, 0x69, 0x67, 0x1a, 0xbe, 0xe0, 0xde, 0xa5, 0x30, 0xb7,
	0x22, 0x2f, 0xe5, 0x42, 0x5c, 0x67, 0x32, 0x14, 0x4f, 0x85, 0xd0, 0x86, 0x50, 0xdc, 0xd1, 0x8e,
	0xa4, 0xc8, 0x43, 0xfe, 0xff, 0x70, 0x5d, 0x92, 0x63, 0xbc, 0xaf, 0x0d, 0xcf, 0xcd, 0x83, 0x91,
	0xa9, 0xd0, 0x86, 0xa7, 0x19, 0x6d, 0x78, 0xc8, 0x6f, 0x86, 0x7b, 0x96, 0x9e, 0xad, 0x59, 0x72,
	0x84, 0xbb, 0x42, 0x2d, 0xb7, 0x64, 0x4d, 0x2b, 0xdb, 0x15, 0x6a, 0xb9, 0x11, 0x0d, 0x5f, 0x1b,
	0xb8, 0xff, 0x65, 0x00, 0x9d, 0x81, 0xd2, 0x82, 0x4c, 0xf1, 0xbf, 0x52, 0xe4, 0xba, 0x9a, 0x95,
	0x22, 0xaf, 0xe9, 0xef, 0x8c, 0xcf, 0x83, 0xda, 0x84, 0x41, 0xad, 0x3f, 0x98, 0x3b, 0x73, 0xb8,
	0xb9, 0x65, 0xf0, 0x86, 0x70, 0xe7, 0x83, 0x25, 0x04, 0xb7, 0x14, 0x4f, 0xd7, 0xe1, 0x2c, 0xfe,
	0xdd, 0x64, 0x55, 0x87, 0x42, 0x49, 0x43, 0x5b, 0xae, 0x43, 0x85, 0x49, 0x0f, 0xb7, 0x4b, 0x9e,
	0x14, 0x82, 0xb6, 0x3d, 0xe4, 0x37, 0x42, 0x57, 0x8c, 0x0b, 0xdc, 0x9e, 0x55, 0x59, 0x48, 0x82,
	0xbb, 0x9f, 0xb2, 0x90, 0x93, 0xef, 0x25, 0xb6, 0x5f, 0x36, 0x38, 0xfd, 0xc9, 0xf3, 0x0c, 0xff,
	0x5c, 0xdc, 0x61, 0x1a, 0x27, 0xf5, 0x9e, 0x29, 0xba, 0x9f, 0xc4, 0xd2, 0xac, 0x8a, 0x28, 0x58,
	0x40, 0xca, 0xae, 0xf8, 0x33, 0xcc, 0xb9, 0xba, 0x01, 0x50, 0x2c, 0x16, 0xca, 0x6e, 0x0e, 0xab,
	0x5d, 0xc8, 0x89, 0x05, 0xd1, 0x5f, 0x2b, 0x39, 0x7b, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x15, 0x5c,
	0x46, 0xc5, 0xb6, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TruthClient is the client API for Truth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TruthClient interface {
	// Returns a classification for a comment
	GetServiceKpi(ctx context.Context, in *GetServiceKpiRequest, opts ...grpc.CallOption) (*GetServiceKpiResponse, error)
}

type truthClient struct {
	cc *grpc.ClientConn
}

func NewTruthClient(cc *grpc.ClientConn) TruthClient {
	return &truthClient{cc}
}

func (c *truthClient) GetServiceKpi(ctx context.Context, in *GetServiceKpiRequest, opts ...grpc.CallOption) (*GetServiceKpiResponse, error) {
	out := new(GetServiceKpiResponse)
	err := c.cc.Invoke(ctx, "/bobsknobshop.truth.v1.Truth/GetServiceKpi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TruthServer is the server API for Truth service.
type TruthServer interface {
	// Returns a classification for a comment
	GetServiceKpi(context.Context, *GetServiceKpiRequest) (*GetServiceKpiResponse, error)
}

func RegisterTruthServer(s *grpc.Server, srv TruthServer) {
	s.RegisterService(&_Truth_serviceDesc, srv)
}

func _Truth_GetServiceKpi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceKpiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TruthServer).GetServiceKpi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.truth.v1.Truth/GetServiceKpi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TruthServer).GetServiceKpi(ctx, req.(*GetServiceKpiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Truth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bobsknobshop.truth.v1.Truth",
	HandlerType: (*TruthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceKpi",
			Handler:    _Truth_GetServiceKpi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bobsknobshop/truth/v1/truth.proto",
}
