// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bobsknobshop/classy/v1/classy.proto

package classy

import (
	fmt "fmt"
	v1 "github.com/HayoVanLoon/genproto/bobsknobshop/common/v1"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Classification struct {
	// Unique resource name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Creation timestamp.
	CreatedOn int64 `protobuf:"varint,2,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	// The version of the service that did the prediction
	ServiceVersion string `protobuf:"bytes,3,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	// Comment ID.
	Comment string `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	// The predicted category.
	Category             string   `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Classification) Reset()         { *m = Classification{} }
func (m *Classification) String() string { return proto.CompactTextString(m) }
func (*Classification) ProtoMessage()    {}
func (*Classification) Descriptor() ([]byte, []int) {
	return fileDescriptor_c90b0c3afe711d5b, []int{0}
}

func (m *Classification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Classification.Unmarshal(m, b)
}
func (m *Classification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Classification.Marshal(b, m, deterministic)
}
func (m *Classification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Classification.Merge(m, src)
}
func (m *Classification) XXX_Size() int {
	return xxx_messageInfo_Classification.Size(m)
}
func (m *Classification) XXX_DiscardUnknown() {
	xxx_messageInfo_Classification.DiscardUnknown(m)
}

var xxx_messageInfo_Classification proto.InternalMessageInfo

func (m *Classification) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Classification) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *Classification) GetServiceVersion() string {
	if m != nil {
		return m.ServiceVersion
	}
	return ""
}

func (m *Classification) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Classification) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type ListClassificationsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListClassificationsRequest) Reset()         { *m = ListClassificationsRequest{} }
func (m *ListClassificationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListClassificationsRequest) ProtoMessage()    {}
func (*ListClassificationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c90b0c3afe711d5b, []int{1}
}

func (m *ListClassificationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClassificationsRequest.Unmarshal(m, b)
}
func (m *ListClassificationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClassificationsRequest.Marshal(b, m, deterministic)
}
func (m *ListClassificationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClassificationsRequest.Merge(m, src)
}
func (m *ListClassificationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListClassificationsRequest.Size(m)
}
func (m *ListClassificationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClassificationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListClassificationsRequest proto.InternalMessageInfo

type ListClassificationsResponse struct {
	Classifications      []*Classification `protobuf:"bytes,1,rep,name=classifications,proto3" json:"classifications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListClassificationsResponse) Reset()         { *m = ListClassificationsResponse{} }
func (m *ListClassificationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListClassificationsResponse) ProtoMessage()    {}
func (*ListClassificationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c90b0c3afe711d5b, []int{2}
}

func (m *ListClassificationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClassificationsResponse.Unmarshal(m, b)
}
func (m *ListClassificationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClassificationsResponse.Marshal(b, m, deterministic)
}
func (m *ListClassificationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClassificationsResponse.Merge(m, src)
}
func (m *ListClassificationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListClassificationsResponse.Size(m)
}
func (m *ListClassificationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClassificationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListClassificationsResponse proto.InternalMessageInfo

func (m *ListClassificationsResponse) GetClassifications() []*Classification {
	if m != nil {
		return m.Classifications
	}
	return nil
}

func init() {
	proto.RegisterType((*Classification)(nil), "bobsknobshop.classy.v1.Classification")
	proto.RegisterType((*ListClassificationsRequest)(nil), "bobsknobshop.classy.v1.ListClassificationsRequest")
	proto.RegisterType((*ListClassificationsResponse)(nil), "bobsknobshop.classy.v1.ListClassificationsResponse")
}

func init() {
	proto.RegisterFile("bobsknobshop/classy/v1/classy.proto", fileDescriptor_c90b0c3afe711d5b)
}

var fileDescriptor_c90b0c3afe711d5b = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4f, 0x6b, 0xe2, 0x40,
	0x14, 0x77, 0x56, 0xd7, 0x5d, 0x67, 0x41, 0x61, 0x16, 0x96, 0x6c, 0x74, 0x59, 0x49, 0xa1, 0xf5,
	0x94, 0x41, 0x3d, 0x96, 0x5e, 0xea, 0xa5, 0x07, 0xa1, 0x92, 0x83, 0x87, 0x22, 0xc8, 0x24, 0x1d,
	0xe3, 0x50, 0x33, 0x2f, 0xcd, 0x8c, 0x81, 0xdc, 0xfa, 0x59, 0xfa, 0xed, 0xfa, 0x2d, 0x4a, 0x26,
	0xd3, 0x52, 0x25, 0x42, 0x7b, 0x7b, 0xef, 0xfd, 0xfe, 0xcd, 0x7b, 0x0c, 0x3e, 0x0b, 0x21, 0x54,
	0x0f, 0x12, 0x42, 0xb5, 0x85, 0x94, 0x46, 0x3b, 0xa6, 0x54, 0x41, 0xf3, 0xb1, 0xad, 0xfc, 0x34,
	0x03, 0x0d, 0xe4, 0xcf, 0x47, 0x92, 0x6f, 0xa1, 0x7c, 0xec, 0x0e, 0x62, 0x80, 0x78, 0xc7, 0x29,
	0x4b, 0x05, 0x65, 0x52, 0x82, 0x66, 0x5a, 0x80, 0x54, 0x95, 0xca, 0xed, 0x5b, 0xd4, 0x74, 0xe1,
	0x7e, 0x43, 0x79, 0x92, 0x6a, 0x6b, 0xe9, 0x1e, 0xe5, 0x42, 0x92, 0x80, 0x34, 0xb9, 0xa6, 0xaa,
	0x48, 0xde, 0x33, 0xc2, 0xdd, 0x59, 0x99, 0x26, 0x36, 0x22, 0x32, 0xde, 0x84, 0xe0, 0x96, 0x64,
	0x09, 0x77, 0xd0, 0x10, 0x8d, 0x3a, 0x81, 0xa9, 0xc9, 0x3f, 0x8c, 0xa3, 0x8c, 0x33, 0xcd, 0xef,
	0xd7, 0x20, 0x9d, 0x6f, 0x43, 0x34, 0x6a, 0x06, 0x1d, 0x3b, 0xb9, 0x95, 0xe4, 0x02, 0xf7, 0x14,
	0xcf, 0x72, 0x11, 0xf1, 0x75, 0xce, 0x33, 0x25, 0x40, 0x3a, 0x4d, 0xa3, 0xee, 0xda, 0xf1, 0xb2,
	0x9a, 0x12, 0x07, 0xff, 0x28, 0xe3, 0xb9, 0xd4, 0x4e, 0xcb, 0x10, 0xde, 0x5a, 0xe2, 0xe2, 0x9f,
	0x11, 0xd3, 0x3c, 0x86, 0xac, 0x70, 0xbe, 0x1b, 0xe8, 0xbd, 0xf7, 0x06, 0xd8, 0x9d, 0x0b, 0xa5,
	0x0f, 0xdf, 0xa9, 0x02, 0xfe, 0xb8, 0xe7, 0x4a, 0x7b, 0x80, 0xfb, 0xb5, 0xa8, 0x4a, 0x41, 0x2a,
	0x4e, 0x16, 0xb8, 0x17, 0x1d, 0x42, 0x0e, 0x1a, 0x36, 0x47, 0xbf, 0x26, 0xe7, 0x7e, 0xfd, 0xcd,
	0xfd, 0x43, 0xa7, 0xe0, 0x58, 0x3e, 0x79, 0x41, 0xb8, 0x6d, 0x38, 0x05, 0x59, 0xe1, 0x9e, 0x65,
	0x17, 0x33, 0xbb, 0xc8, 0xff, 0x23, 0xdb, 0xea, 0xda, 0xa5, 0x6d, 0x45, 0x70, 0x3f, 0x99, 0xeb,
	0x35, 0xc8, 0x13, 0xc2, 0xbf, 0x6b, 0x56, 0x23, 0x93, 0x53, 0x0e, 0xa7, 0xaf, 0xe4, 0x4e, 0xbf,
	0xa4, 0xa9, 0x6e, 0xe7, 0x35, 0xae, 0x57, 0xf8, 0x6f, 0xbc, 0x3b, 0x21, 0x5d, 0xa0, 0xbb, 0xab,
	0x58, 0xe8, 0xed, 0x3e, 0x2c, 0xb7, 0xa4, 0x37, 0xac, 0x80, 0x25, 0x93, 0x73, 0x00, 0x49, 0x63,
	0x2e, 0xcd, 0xff, 0xa2, 0xf5, 0x7f, 0xff, 0xb2, 0xaa, 0xc2, 0xb6, 0x21, 0x4d, 0x5f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x8f, 0xdf, 0x74, 0x57, 0x23, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClassyClient is the client API for Classy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClassyClient interface {
	// Returns a classification for a comment
	ClassifyComment(ctx context.Context, in *v1.Comment, opts ...grpc.CallOption) (*Classification, error)
	// Returns all classifications
	// TODO: debug, remove before go-live
	ListClassifications(ctx context.Context, in *ListClassificationsRequest, opts ...grpc.CallOption) (*ListClassificationsResponse, error)
}

type classyClient struct {
	cc *grpc.ClientConn
}

func NewClassyClient(cc *grpc.ClientConn) ClassyClient {
	return &classyClient{cc}
}

func (c *classyClient) ClassifyComment(ctx context.Context, in *v1.Comment, opts ...grpc.CallOption) (*Classification, error) {
	out := new(Classification)
	err := c.cc.Invoke(ctx, "/bobsknobshop.classy.v1.Classy/ClassifyComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classyClient) ListClassifications(ctx context.Context, in *ListClassificationsRequest, opts ...grpc.CallOption) (*ListClassificationsResponse, error) {
	out := new(ListClassificationsResponse)
	err := c.cc.Invoke(ctx, "/bobsknobshop.classy.v1.Classy/ListClassifications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClassyServer is the server API for Classy service.
type ClassyServer interface {
	// Returns a classification for a comment
	ClassifyComment(context.Context, *v1.Comment) (*Classification, error)
	// Returns all classifications
	// TODO: debug, remove before go-live
	ListClassifications(context.Context, *ListClassificationsRequest) (*ListClassificationsResponse, error)
}

func RegisterClassyServer(s *grpc.Server, srv ClassyServer) {
	s.RegisterService(&_Classy_serviceDesc, srv)
}

func _Classy_ClassifyComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Comment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassyServer).ClassifyComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.classy.v1.Classy/ClassifyComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassyServer).ClassifyComment(ctx, req.(*v1.Comment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Classy_ListClassifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClassificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassyServer).ListClassifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.classy.v1.Classy/ListClassifications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassyServer).ListClassifications(ctx, req.(*ListClassificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Classy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bobsknobshop.classy.v1.Classy",
	HandlerType: (*ClassyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClassifyComment",
			Handler:    _Classy_ClassifyComment_Handler,
		},
		{
			MethodName: "ListClassifications",
			Handler:    _Classy_ListClassifications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bobsknobshop/classy/v1/classy.proto",
}
