// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bobsknobshop/classy/v1/types.proto

package classy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClassifyResponse struct {
	Category             int32         `protobuf:"varint,1,opt,name=category,proto3" json:"category,omitempty"`
	Meta                 *ClassifyMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ClassifyResponse) Reset()         { *m = ClassifyResponse{} }
func (m *ClassifyResponse) String() string { return proto.CompactTextString(m) }
func (*ClassifyResponse) ProtoMessage()    {}
func (*ClassifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_493f33bc69a8f4e9, []int{0}
}

func (m *ClassifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassifyResponse.Unmarshal(m, b)
}
func (m *ClassifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassifyResponse.Marshal(b, m, deterministic)
}
func (m *ClassifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassifyResponse.Merge(m, src)
}
func (m *ClassifyResponse) XXX_Size() int {
	return xxx_messageInfo_ClassifyResponse.Size(m)
}
func (m *ClassifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClassifyResponse proto.InternalMessageInfo

func (m *ClassifyResponse) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *ClassifyResponse) GetMeta() *ClassifyMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ClassifyMeta struct {
	Mapping              map[string]int32 `protobuf:"bytes,1,rep,name=mapping,proto3" json:"mapping,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ClassifyMeta) Reset()         { *m = ClassifyMeta{} }
func (m *ClassifyMeta) String() string { return proto.CompactTextString(m) }
func (*ClassifyMeta) ProtoMessage()    {}
func (*ClassifyMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_493f33bc69a8f4e9, []int{1}
}

func (m *ClassifyMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassifyMeta.Unmarshal(m, b)
}
func (m *ClassifyMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassifyMeta.Marshal(b, m, deterministic)
}
func (m *ClassifyMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassifyMeta.Merge(m, src)
}
func (m *ClassifyMeta) XXX_Size() int {
	return xxx_messageInfo_ClassifyMeta.Size(m)
}
func (m *ClassifyMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassifyMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ClassifyMeta proto.InternalMessageInfo

func (m *ClassifyMeta) GetMapping() map[string]int32 {
	if m != nil {
		return m.Mapping
	}
	return nil
}

func init() {
	proto.RegisterType((*ClassifyResponse)(nil), "bobsknobshop.classy.v1.ClassifyResponse")
	proto.RegisterType((*ClassifyMeta)(nil), "bobsknobshop.classy.v1.ClassifyMeta")
	proto.RegisterMapType((map[string]int32)(nil), "bobsknobshop.classy.v1.ClassifyMeta.MappingEntry")
}

func init() { proto.RegisterFile("bobsknobshop/classy/v1/types.proto", fileDescriptor_493f33bc69a8f4e9) }

var fileDescriptor_493f33bc69a8f4e9 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4d, 0x4b, 0xc3, 0x30,
	0x18, 0xc7, 0xc9, 0xe6, 0x7c, 0xc9, 0x76, 0x18, 0x41, 0xa4, 0x16, 0x0f, 0xa5, 0x78, 0xe8, 0x29,
	0xa1, 0xf3, 0x32, 0x26, 0x5e, 0x14, 0x41, 0xd0, 0x81, 0xe4, 0xe0, 0x41, 0xbc, 0xa4, 0x25, 0xa6,
	0x65, 0x6d, 0x9e, 0xd0, 0x64, 0x85, 0x7c, 0x12, 0xbf, 0xae, 0xac, 0x75, 0xd2, 0xc3, 0x04, 0x6f,
	0xcf, 0x93, 0xfc, 0xfe, 0x2f, 0x24, 0x38, 0xce, 0x20, 0xb3, 0x1b, 0x0d, 0x99, 0x2d, 0xc0, 0xb0,
	0xbc, 0x12, 0xd6, 0x7a, 0xd6, 0xa6, 0xcc, 0x79, 0x23, 0x2d, 0x35, 0x0d, 0x38, 0x20, 0x17, 0x43,
	0x86, 0xf6, 0x0c, 0x6d, 0xd3, 0xf0, 0x4a, 0x01, 0xa8, 0x4a, 0x32, 0x61, 0x4a, 0x26, 0xb4, 0x06,
	0x27, 0x5c, 0x09, 0xfa, 0x47, 0x15, 0x17, 0x78, 0xfe, 0xb0, 0x43, 0xcb, 0x4f, 0xcf, 0xa5, 0x35,
	0xa0, 0xad, 0x24, 0x21, 0x3e, 0xcd, 0x85, 0x93, 0x0a, 0x1a, 0x1f, 0xa0, 0x08, 0x25, 0x13, 0xfe,
	0xbb, 0x93, 0x25, 0x3e, 0xaa, 0xa5, 0x13, 0xc1, 0x28, 0x42, 0xc9, 0x74, 0x71, 0x4d, 0x0f, 0x87,
	0xd2, 0xbd, 0xe7, 0x5a, 0x3a, 0xc1, 0x3b, 0x45, 0xfc, 0x85, 0xf0, 0x6c, 0x78, 0x4c, 0x9e, 0xf1,
	0x49, 0x2d, 0x8c, 0x29, 0xb5, 0x0a, 0x50, 0x34, 0x4e, 0xa6, 0x8b, 0xf4, 0x3f, 0x6e, 0x74, 0xdd,
	0x6b, 0x1e, 0xb5, 0x6b, 0x3c, 0xdf, 0x3b, 0x84, 0x2b, 0x3c, 0x1b, 0x5e, 0x90, 0x39, 0x1e, 0x6f,
	0x64, 0x5f, 0xff, 0x8c, 0xef, 0x46, 0x72, 0x8e, 0x27, 0xad, 0xa8, 0xb6, 0xb2, 0xab, 0x3e, 0xe1,
	0xfd, 0xb2, 0x1a, 0x2d, 0xd1, 0xfd, 0x07, 0xbe, 0x54, 0xd5, 0x1f, 0xd9, 0xaf, 0xe8, 0xfd, 0x4e,
	0x95, 0xae, 0xd8, 0x66, 0x34, 0x87, 0x9a, 0x3d, 0x09, 0x0f, 0x6f, 0x42, 0xbf, 0x00, 0x68, 0xa6,
	0xa4, 0xee, 0xde, 0x90, 0x1d, 0xfe, 0x9c, 0xdb, 0x7e, 0xca, 0x8e, 0x3b, 0xe8, 0xe6, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0x1c, 0x85, 0x5e, 0xde, 0xc4, 0x01, 0x00, 0x00,
}
