// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bobsknobshop/common/v1/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	money "google.golang.org/genproto/googleapis/type/money"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Comment struct {
	// Unique name for comment.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Timestamp comment was recorded.
	CreatedOn int64 `protobuf:"varint,2,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	// Topic the comment is aimed at
	Topic string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	// The name of the author of the comment.
	Author string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	// The comment body.
	Text                 string   `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccf49567d065ceb3, []int{0}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Comment) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *Comment) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Comment) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Comment) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Order struct {
	// Unique name for order.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Timestamp order was recorded.
	CreatedOn int64 `protobuf:"varint,2,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	// Customer ID.
	Client string `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	// Order total
	Total *money.Money `protobuf:"bytes,6,opt,name=total,proto3" json:"total,omitempty"`
	// The ordered items
	OrderLines           []*Order_OrderLine `protobuf:"bytes,7,rep,name=order_lines,json=orderLines,proto3" json:"order_lines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccf49567d065ceb3, []int{1}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Order) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *Order) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *Order) GetTotal() *money.Money {
	if m != nil {
		return m.Total
	}
	return nil
}

func (m *Order) GetOrderLines() []*Order_OrderLine {
	if m != nil {
		return m.OrderLines
	}
	return nil
}

type Order_OrderLine struct {
	// Unique name for order.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Product ID.
	Sku string `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	// Number of items ordered.
	Quantity int32 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Order line total.
	Total                *money.Money `protobuf:"bytes,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Order_OrderLine) Reset()         { *m = Order_OrderLine{} }
func (m *Order_OrderLine) String() string { return proto.CompactTextString(m) }
func (*Order_OrderLine) ProtoMessage()    {}
func (*Order_OrderLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccf49567d065ceb3, []int{1, 0}
}

func (m *Order_OrderLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order_OrderLine.Unmarshal(m, b)
}
func (m *Order_OrderLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order_OrderLine.Marshal(b, m, deterministic)
}
func (m *Order_OrderLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order_OrderLine.Merge(m, src)
}
func (m *Order_OrderLine) XXX_Size() int {
	return xxx_messageInfo_Order_OrderLine.Size(m)
}
func (m *Order_OrderLine) XXX_DiscardUnknown() {
	xxx_messageInfo_Order_OrderLine.DiscardUnknown(m)
}

var xxx_messageInfo_Order_OrderLine proto.InternalMessageInfo

func (m *Order_OrderLine) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Order_OrderLine) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *Order_OrderLine) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Order_OrderLine) GetTotal() *money.Money {
	if m != nil {
		return m.Total
	}
	return nil
}

func init() {
	proto.RegisterType((*Comment)(nil), "bobsknobshop.common.v1.Comment")
	proto.RegisterType((*Order)(nil), "bobsknobshop.common.v1.Order")
	proto.RegisterType((*Order_OrderLine)(nil), "bobsknobshop.common.v1.Order.OrderLine")
}

func init() {
	proto.RegisterFile("bobsknobshop/common/v1/common.proto", fileDescriptor_ccf49567d065ceb3)
}

var fileDescriptor_ccf49567d065ceb3 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xb1, 0x8e, 0xd3, 0x40,
	0x10, 0x95, 0xe3, 0xd8, 0xc1, 0x9b, 0x06, 0xad, 0x50, 0x30, 0x16, 0x48, 0x56, 0x28, 0x70, 0xe5,
	0x55, 0x42, 0x89, 0x68, 0xa0, 0x49, 0x11, 0x14, 0xe4, 0x82, 0x02, 0x21, 0x45, 0x6b, 0x67, 0xe5,
	0xac, 0x62, 0xcf, 0x18, 0x7b, 0x1d, 0x70, 0xc3, 0xaf, 0xf1, 0x6b, 0xa7, 0xdd, 0x75, 0x72, 0x57,
	0xe4, 0x74, 0xd2, 0x35, 0xd6, 0x9b, 0x79, 0xb3, 0x7e, 0xf3, 0x9e, 0x86, 0xbc, 0xcf, 0x31, 0xef,
	0x4e, 0x80, 0x79, 0x77, 0xc4, 0x86, 0x15, 0x58, 0xd7, 0x08, 0xec, 0xbc, 0x1a, 0x51, 0xda, 0xb4,
	0xa8, 0x90, 0x2e, 0x1e, 0x0e, 0xa5, 0x23, 0x75, 0x5e, 0x45, 0xaf, 0x4b, 0xc4, 0xb2, 0x12, 0x4c,
	0x0d, 0x8d, 0x60, 0x35, 0x82, 0x18, 0xec, 0x83, 0xe8, 0xed, 0x48, 0xf0, 0x46, 0x32, 0x0e, 0x80,
	0x8a, 0x2b, 0x89, 0xd0, 0x59, 0x76, 0xf9, 0x8f, 0xcc, 0xbe, 0x62, 0x5d, 0x0b, 0x50, 0x94, 0x92,
	0x29, 0xf0, 0x5a, 0x84, 0x4e, 0xec, 0x24, 0x41, 0x66, 0x30, 0x7d, 0x47, 0x48, 0xd1, 0x0a, 0xae,
	0xc4, 0x61, 0x8f, 0x10, 0x4e, 0x62, 0x27, 0x71, 0xb3, 0x60, 0xec, 0xec, 0x80, 0xbe, 0x22, 0x9e,
	0xc2, 0x46, 0x16, 0xa1, 0x6b, 0xde, 0xd8, 0x82, 0x2e, 0x88, 0xcf, 0x7b, 0x75, 0xc4, 0x36, 0x9c,
	0x9a, 0xf6, 0x58, 0x69, 0x01, 0x25, 0xfe, 0xaa, 0xd0, 0xb3, 0x02, 0x1a, 0x2f, 0xff, 0x4f, 0x88,
	0xb7, 0x6b, 0x0f, 0xa2, 0x7d, 0x8e, 0xfc, 0x82, 0xf8, 0x45, 0x25, 0x05, 0x5c, 0x7e, 0x39, 0x56,
	0x34, 0xd1, 0x6b, 0x29, 0x5e, 0x85, 0x7e, 0xec, 0x24, 0xf3, 0x35, 0x4d, 0x6d, 0x04, 0xa9, 0xce,
	0x26, 0xfd, 0xa6, 0xb3, 0xc9, 0xec, 0x00, 0xdd, 0x90, 0x39, 0x6a, 0xf5, 0x7d, 0x25, 0x41, 0x74,
	0xe1, 0x2c, 0x76, 0x93, 0xf9, 0xfa, 0x43, 0x7a, 0x3b, 0xe3, 0xd4, 0x2c, 0x6a, 0xbf, 0x5b, 0x09,
	0x22, 0x23, 0x78, 0x81, 0x5d, 0xf4, 0x87, 0x04, 0x57, 0xe2, 0xa6, 0x97, 0x97, 0xc4, 0xed, 0x4e,
	0xbd, 0x31, 0x11, 0x64, 0x1a, 0xd2, 0x88, 0xbc, 0xf8, 0xdd, 0x73, 0x50, 0x52, 0x0d, 0x26, 0x40,
	0x2f, 0xbb, 0xd6, 0xf7, 0x16, 0xa6, 0x4f, 0x58, 0xf8, 0xf2, 0x8b, 0xbc, 0x29, 0xab, 0x47, 0x36,
	0xfe, 0xee, 0xfc, 0xfc, 0x5c, 0x4a, 0x75, 0xec, 0x73, 0xdd, 0x63, 0x1b, 0x3e, 0xe0, 0x0f, 0x0e,
	0x5b, 0x44, 0x60, 0xa5, 0x00, 0x73, 0x01, 0xec, 0xf6, 0xd1, 0x7d, 0xb2, 0x28, 0xf7, 0xcd, 0xd0,
	0xc7, 0xbb, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x1e, 0x1b, 0x7c, 0x9c, 0x02, 0x00, 0x00,
}
