// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bobsknobshop/commentcentre/v1/commentcentre.proto

package commentcentre

import (
	fmt "fmt"
	v1 "github.com/HayoVanLoon/genproto/bobsknobshop/common/v1"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListCommentsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCommentsRequest) Reset()         { *m = ListCommentsRequest{} }
func (m *ListCommentsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCommentsRequest) ProtoMessage()    {}
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1871a1b004822c1, []int{0}
}

func (m *ListCommentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommentsRequest.Unmarshal(m, b)
}
func (m *ListCommentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommentsRequest.Marshal(b, m, deterministic)
}
func (m *ListCommentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommentsRequest.Merge(m, src)
}
func (m *ListCommentsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCommentsRequest.Size(m)
}
func (m *ListCommentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommentsRequest proto.InternalMessageInfo

type ListCommentsResponse struct {
	Comments             []*v1.Comment `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListCommentsResponse) Reset()         { *m = ListCommentsResponse{} }
func (m *ListCommentsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCommentsResponse) ProtoMessage()    {}
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1871a1b004822c1, []int{1}
}

func (m *ListCommentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommentsResponse.Unmarshal(m, b)
}
func (m *ListCommentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommentsResponse.Marshal(b, m, deterministic)
}
func (m *ListCommentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommentsResponse.Merge(m, src)
}
func (m *ListCommentsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCommentsResponse.Size(m)
}
func (m *ListCommentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommentsResponse proto.InternalMessageInfo

func (m *ListCommentsResponse) GetComments() []*v1.Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func init() {
	proto.RegisterType((*ListCommentsRequest)(nil), "bobsknobshop.commentcentre.v1.ListCommentsRequest")
	proto.RegisterType((*ListCommentsResponse)(nil), "bobsknobshop.commentcentre.v1.ListCommentsResponse")
}

func init() {
	proto.RegisterFile("bobsknobshop/commentcentre/v1/commentcentre.proto", fileDescriptor_b1871a1b004822c1)
}

var fileDescriptor_b1871a1b004822c1 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x1b, 0x04, 0x91, 0xd5, 0x5e, 0x56, 0x05, 0x09, 0x8a, 0x25, 0x5e, 0x3c, 0xed, 0x92,
	0xf4, 0xd8, 0x9b, 0xb9, 0x08, 0xf6, 0x20, 0x2d, 0x78, 0xf0, 0xb6, 0x29, 0xc3, 0x36, 0xd8, 0xce,
	0xa4, 0x99, 0x69, 0xa0, 0xbf, 0xd6, 0xbf, 0x22, 0x36, 0x51, 0x12, 0x2a, 0x29, 0x5e, 0xdf, 0xbe,
	0x6f, 0xe6, 0xcd, 0xec, 0xa8, 0x38, 0xa3, 0x8c, 0x3f, 0x90, 0x32, 0x5e, 0x52, 0x61, 0x17, 0xb4,
	0x5e, 0x03, 0xca, 0x02, 0x50, 0x4a, 0xb0, 0x55, 0xdc, 0x15, 0x4c, 0x51, 0x92, 0x90, 0xbe, 0x6b,
	0x23, 0xa6, 0xeb, 0xa8, 0xe2, 0xf0, 0xd6, 0x13, 0xf9, 0x15, 0x58, 0x57, 0xe4, 0xd6, 0x21, 0x92,
	0x38, 0xc9, 0x09, 0xb9, 0x86, 0xc3, 0x87, 0x83, 0x7e, 0x84, 0x3f, 0x8d, 0x08, 0x6b, 0x53, 0x74,
	0xad, 0x2e, 0xa7, 0x39, 0x4b, 0x5a, 0x97, 0xe6, 0x19, 0x6c, 0xb6, 0xc0, 0x12, 0xcd, 0xd5, 0x55,
	0x57, 0xe6, 0x82, 0x90, 0x41, 0x4f, 0xd4, 0x59, 0x93, 0x82, 0x6f, 0x82, 0xd1, 0xc9, 0xe3, 0x79,
	0x72, 0x6f, 0x0e, 0x32, 0x12, 0x9a, 0x2a, 0x36, 0x0d, 0x3b, 0xfb, 0x05, 0x92, 0xcf, 0x40, 0x0d,
	0xd3, 0xf6, 0x0c, 0x7a, 0xae, 0x86, 0x69, 0x09, 0x4e, 0xa0, 0x91, 0xf5, 0xb1, 0x6a, 0xe1, 0x31,
	0x43, 0x34, 0xd0, 0x3b, 0x75, 0xd1, 0xce, 0xae, 0x13, 0xd3, 0xbb, 0x45, 0xf3, 0xc7, 0xfc, 0xe1,
	0xf8, 0x5f, 0x4c, 0xbd, 0x9c, 0x68, 0xf0, 0xb4, 0x51, 0x23, 0xbf, 0xea, 0x47, 0x5f, 0x83, 0xf7,
	0x17, 0x9f, 0xcb, 0x72, 0x9b, 0x7d, 0x3f, 0xd9, 0x67, 0xb7, 0xa3, 0x37, 0x87, 0x53, 0x22, 0xb4,
	0x1e, 0x70, 0xff, 0x29, 0xb6, 0xf7, 0x50, 0x26, 0x1d, 0x21, 0x3b, 0xdd, 0x23, 0xe3, 0xaf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x2d, 0x1e, 0x44, 0x9a, 0x5e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommentcentreClient is the client API for Commentcentre service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommentcentreClient interface {
	// Returns a classification for a comment
	CreateComment(ctx context.Context, in *v1.Comment, opts ...grpc.CallOption) (*v1.Comment, error)
	// Returns all comments
	// TODO: debug, remove before go-live
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
}

type commentcentreClient struct {
	cc *grpc.ClientConn
}

func NewCommentcentreClient(cc *grpc.ClientConn) CommentcentreClient {
	return &commentcentreClient{cc}
}

func (c *commentcentreClient) CreateComment(ctx context.Context, in *v1.Comment, opts ...grpc.CallOption) (*v1.Comment, error) {
	out := new(v1.Comment)
	err := c.cc.Invoke(ctx, "/bobsknobshop.commentcentre.v1.Commentcentre/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentcentreClient) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	out := new(ListCommentsResponse)
	err := c.cc.Invoke(ctx, "/bobsknobshop.commentcentre.v1.Commentcentre/ListComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentcentreServer is the server API for Commentcentre service.
type CommentcentreServer interface {
	// Returns a classification for a comment
	CreateComment(context.Context, *v1.Comment) (*v1.Comment, error)
	// Returns all comments
	// TODO: debug, remove before go-live
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error)
}

func RegisterCommentcentreServer(s *grpc.Server, srv CommentcentreServer) {
	s.RegisterService(&_Commentcentre_serviceDesc, srv)
}

func _Commentcentre_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Comment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentcentreServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.commentcentre.v1.Commentcentre/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentcentreServer).CreateComment(ctx, req.(*v1.Comment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commentcentre_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentcentreServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.commentcentre.v1.Commentcentre/ListComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentcentreServer).ListComments(ctx, req.(*ListCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Commentcentre_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bobsknobshop.commentcentre.v1.Commentcentre",
	HandlerType: (*CommentcentreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateComment",
			Handler:    _Commentcentre_CreateComment_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _Commentcentre_ListComments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bobsknobshop/commentcentre/v1/commentcentre.proto",
}
