// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bobsknobshop/commentcentre/v1/commentcentre.proto

package commentcentre

import (
	fmt "fmt"
	v1 "github.com/HayoVanLoon/genproto/bobsknobshop/common/v1"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListCommentsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCommentsRequest) Reset()         { *m = ListCommentsRequest{} }
func (m *ListCommentsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCommentsRequest) ProtoMessage()    {}
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1871a1b004822c1, []int{0}
}

func (m *ListCommentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommentsRequest.Unmarshal(m, b)
}
func (m *ListCommentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommentsRequest.Marshal(b, m, deterministic)
}
func (m *ListCommentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommentsRequest.Merge(m, src)
}
func (m *ListCommentsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCommentsRequest.Size(m)
}
func (m *ListCommentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommentsRequest proto.InternalMessageInfo

type ListCommentsResponse struct {
	Comments             []*v1.Comment `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListCommentsResponse) Reset()         { *m = ListCommentsResponse{} }
func (m *ListCommentsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCommentsResponse) ProtoMessage()    {}
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1871a1b004822c1, []int{1}
}

func (m *ListCommentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommentsResponse.Unmarshal(m, b)
}
func (m *ListCommentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommentsResponse.Marshal(b, m, deterministic)
}
func (m *ListCommentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommentsResponse.Merge(m, src)
}
func (m *ListCommentsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCommentsResponse.Size(m)
}
func (m *ListCommentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommentsResponse proto.InternalMessageInfo

func (m *ListCommentsResponse) GetComments() []*v1.Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

type ListUpdatesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUpdatesRequest) Reset()         { *m = ListUpdatesRequest{} }
func (m *ListUpdatesRequest) String() string { return proto.CompactTextString(m) }
func (*ListUpdatesRequest) ProtoMessage()    {}
func (*ListUpdatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1871a1b004822c1, []int{2}
}

func (m *ListUpdatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUpdatesRequest.Unmarshal(m, b)
}
func (m *ListUpdatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUpdatesRequest.Marshal(b, m, deterministic)
}
func (m *ListUpdatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUpdatesRequest.Merge(m, src)
}
func (m *ListUpdatesRequest) XXX_Size() int {
	return xxx_messageInfo_ListUpdatesRequest.Size(m)
}
func (m *ListUpdatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUpdatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUpdatesRequest proto.InternalMessageInfo

type ListUpdatesResponse struct {
	// Move operations from one category to another
	Moves                []*ListUpdatesResponse_Move `protobuf:"bytes,10,rep,name=moves,proto3" json:"moves,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ListUpdatesResponse) Reset()         { *m = ListUpdatesResponse{} }
func (m *ListUpdatesResponse) String() string { return proto.CompactTextString(m) }
func (*ListUpdatesResponse) ProtoMessage()    {}
func (*ListUpdatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1871a1b004822c1, []int{3}
}

func (m *ListUpdatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUpdatesResponse.Unmarshal(m, b)
}
func (m *ListUpdatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUpdatesResponse.Marshal(b, m, deterministic)
}
func (m *ListUpdatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUpdatesResponse.Merge(m, src)
}
func (m *ListUpdatesResponse) XXX_Size() int {
	return xxx_messageInfo_ListUpdatesResponse.Size(m)
}
func (m *ListUpdatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUpdatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUpdatesResponse proto.InternalMessageInfo

func (m *ListUpdatesResponse) GetMoves() []*ListUpdatesResponse_Move {
	if m != nil {
		return m.Moves
	}
	return nil
}

type ListUpdatesResponse_Move struct {
	Comment              string   `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUpdatesResponse_Move) Reset()         { *m = ListUpdatesResponse_Move{} }
func (m *ListUpdatesResponse_Move) String() string { return proto.CompactTextString(m) }
func (*ListUpdatesResponse_Move) ProtoMessage()    {}
func (*ListUpdatesResponse_Move) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1871a1b004822c1, []int{3, 0}
}

func (m *ListUpdatesResponse_Move) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUpdatesResponse_Move.Unmarshal(m, b)
}
func (m *ListUpdatesResponse_Move) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUpdatesResponse_Move.Marshal(b, m, deterministic)
}
func (m *ListUpdatesResponse_Move) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUpdatesResponse_Move.Merge(m, src)
}
func (m *ListUpdatesResponse_Move) XXX_Size() int {
	return xxx_messageInfo_ListUpdatesResponse_Move.Size(m)
}
func (m *ListUpdatesResponse_Move) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUpdatesResponse_Move.DiscardUnknown(m)
}

var xxx_messageInfo_ListUpdatesResponse_Move proto.InternalMessageInfo

func (m *ListUpdatesResponse_Move) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *ListUpdatesResponse_Move) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ListUpdatesResponse_Move) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func init() {
	proto.RegisterType((*ListCommentsRequest)(nil), "bobsknobshop.commentcentre.v1.ListCommentsRequest")
	proto.RegisterType((*ListCommentsResponse)(nil), "bobsknobshop.commentcentre.v1.ListCommentsResponse")
	proto.RegisterType((*ListUpdatesRequest)(nil), "bobsknobshop.commentcentre.v1.ListUpdatesRequest")
	proto.RegisterType((*ListUpdatesResponse)(nil), "bobsknobshop.commentcentre.v1.ListUpdatesResponse")
	proto.RegisterType((*ListUpdatesResponse_Move)(nil), "bobsknobshop.commentcentre.v1.ListUpdatesResponse.Move")
}

func init() {
	proto.RegisterFile("bobsknobshop/commentcentre/v1/commentcentre.proto", fileDescriptor_b1871a1b004822c1)
}

var fileDescriptor_b1871a1b004822c1 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0x4e, 0xfa, 0x40,
	0x10, 0xc6, 0x69, 0xe1, 0xff, 0x57, 0x07, 0xf1, 0xb0, 0x62, 0xd2, 0x34, 0x1a, 0x49, 0xbd, 0x70,
	0xda, 0xa6, 0xe5, 0xe0, 0x81, 0x9b, 0x78, 0x30, 0x11, 0x12, 0x53, 0xa2, 0x07, 0x6f, 0x2d, 0xae,
	0xa5, 0x91, 0xee, 0x94, 0xee, 0xd2, 0x84, 0x57, 0xf2, 0x85, 0x7c, 0x1d, 0x43, 0xb7, 0x90, 0x56,
	0x0c, 0xc8, 0xad, 0xfb, 0x75, 0x7e, 0xf3, 0x4d, 0xbf, 0xe9, 0x82, 0x13, 0x60, 0x20, 0x3e, 0x38,
	0x06, 0x62, 0x8a, 0x89, 0x3d, 0xc1, 0x38, 0x66, 0x5c, 0x4e, 0x18, 0x97, 0x29, 0xb3, 0x33, 0xa7,
	0x2a, 0xd0, 0x24, 0x45, 0x89, 0xe4, 0xaa, 0x8c, 0xd0, 0x6a, 0x45, 0xe6, 0x98, 0x97, 0x21, 0x62,
	0x38, 0x63, 0xb6, 0x9f, 0x44, 0xb6, 0xcf, 0x39, 0x4a, 0x5f, 0x46, 0xc8, 0x85, 0x82, 0xcd, 0x9b,
	0x2d, 0x3f, 0xe4, 0x6b, 0x23, 0xe4, 0xaa, 0xc8, 0xba, 0x80, 0xf3, 0x61, 0x24, 0xe4, 0x40, 0xb5,
	0x16, 0x1e, 0x9b, 0x2f, 0x98, 0x90, 0xd6, 0x18, 0xda, 0x55, 0x59, 0x24, 0xc8, 0x05, 0x23, 0x7d,
	0x38, 0x2e, 0xa6, 0x10, 0x86, 0xd6, 0xa9, 0x77, 0x9b, 0xee, 0x35, 0xdd, 0x9a, 0x11, 0x39, 0xcd,
	0x1c, 0x5a, 0xb0, 0xde, 0x06, 0xb0, 0xda, 0x40, 0x56, 0x4d, 0x9f, 0x93, 0x37, 0x5f, 0xb2, 0x8d,
	0xd5, 0xa7, 0xa6, 0x46, 0xd8, 0xc8, 0x85, 0xd5, 0x08, 0xfe, 0xc5, 0x98, 0x31, 0x61, 0x40, 0xee,
	0x73, 0x4b, 0x77, 0x66, 0x41, 0x7f, 0x69, 0x41, 0x47, 0x98, 0x31, 0x4f, 0x75, 0x31, 0xef, 0xa1,
	0xb1, 0x3a, 0x12, 0x03, 0x8e, 0x0a, 0xd6, 0xd0, 0x3a, 0x5a, 0xf7, 0xc4, 0x5b, 0x1f, 0x09, 0x81,
	0xc6, 0x7b, 0x8a, 0xb1, 0xa1, 0xe7, 0x72, 0xfe, 0x4c, 0xce, 0x40, 0x97, 0x68, 0xd4, 0x73, 0x45,
	0x97, 0xe8, 0x7e, 0xe9, 0xd0, 0x1a, 0x94, 0xad, 0xc9, 0x18, 0x5a, 0x83, 0x94, 0xf9, 0x92, 0x15,
	0x32, 0xd9, 0x17, 0x88, 0xb9, 0xaf, 0xc0, 0xaa, 0x91, 0x25, 0x9c, 0x96, 0xe3, 0x27, 0xee, 0x1f,
	0x3e, 0xfe, 0xc7, 0x0a, 0xcd, 0xde, 0x41, 0x8c, 0x4a, 0xcc, 0xaa, 0x91, 0x0c, 0x9a, 0xa5, 0x28,
	0x89, 0x73, 0x48, 0xec, 0xca, 0xd8, 0x3d, 0x7c, 0x53, 0x56, 0xed, 0x6e, 0x0e, 0x9d, 0x70, 0xb6,
	0x9b, 0x7c, 0xd2, 0x5e, 0x1f, 0xc3, 0x48, 0x4e, 0x17, 0xc1, 0xea, 0x95, 0xfd, 0xe0, 0x2f, 0xf1,
	0xc5, 0xe7, 0x43, 0x44, 0x6e, 0x87, 0x8c, 0xe7, 0xff, 0xb3, 0xbd, 0xf3, 0x8e, 0xf5, 0x2b, 0x42,
	0xf0, 0x3f, 0x47, 0x7a, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xc6, 0xa2, 0xca, 0x99, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommentcentreClient is the client API for Commentcentre service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommentcentreClient interface {
	// Returns a classification for a comment
	CreateComment(ctx context.Context, in *v1.Comment, opts ...grpc.CallOption) (*v1.Comment, error)
	// Returns all comments
	// TODO: add paging or deprecate
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
	ListUpdates(ctx context.Context, in *ListUpdatesRequest, opts ...grpc.CallOption) (*ListUpdatesResponse, error)
}

type commentcentreClient struct {
	cc *grpc.ClientConn
}

func NewCommentcentreClient(cc *grpc.ClientConn) CommentcentreClient {
	return &commentcentreClient{cc}
}

func (c *commentcentreClient) CreateComment(ctx context.Context, in *v1.Comment, opts ...grpc.CallOption) (*v1.Comment, error) {
	out := new(v1.Comment)
	err := c.cc.Invoke(ctx, "/bobsknobshop.commentcentre.v1.Commentcentre/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentcentreClient) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	out := new(ListCommentsResponse)
	err := c.cc.Invoke(ctx, "/bobsknobshop.commentcentre.v1.Commentcentre/ListComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentcentreClient) ListUpdates(ctx context.Context, in *ListUpdatesRequest, opts ...grpc.CallOption) (*ListUpdatesResponse, error) {
	out := new(ListUpdatesResponse)
	err := c.cc.Invoke(ctx, "/bobsknobshop.commentcentre.v1.Commentcentre/ListUpdates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentcentreServer is the server API for Commentcentre service.
type CommentcentreServer interface {
	// Returns a classification for a comment
	CreateComment(context.Context, *v1.Comment) (*v1.Comment, error)
	// Returns all comments
	// TODO: add paging or deprecate
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error)
	ListUpdates(context.Context, *ListUpdatesRequest) (*ListUpdatesResponse, error)
}

func RegisterCommentcentreServer(s *grpc.Server, srv CommentcentreServer) {
	s.RegisterService(&_Commentcentre_serviceDesc, srv)
}

func _Commentcentre_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Comment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentcentreServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.commentcentre.v1.Commentcentre/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentcentreServer).CreateComment(ctx, req.(*v1.Comment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commentcentre_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentcentreServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.commentcentre.v1.Commentcentre/ListComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentcentreServer).ListComments(ctx, req.(*ListCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commentcentre_ListUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUpdatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentcentreServer).ListUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.commentcentre.v1.Commentcentre/ListUpdates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentcentreServer).ListUpdates(ctx, req.(*ListUpdatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Commentcentre_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bobsknobshop.commentcentre.v1.Commentcentre",
	HandlerType: (*CommentcentreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateComment",
			Handler:    _Commentcentre_CreateComment_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _Commentcentre_ListComments_Handler,
		},
		{
			MethodName: "ListUpdates",
			Handler:    _Commentcentre_ListUpdates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bobsknobshop/commentcentre/v1/commentcentre.proto",
}
