//
// Copyright 2019 Hayo van Loon
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.9.2
// source: greeter/greeter.proto

package greeter

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Greeting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Greeting) Reset() {
	*x = Greeting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_greeter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Greeting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Greeting) ProtoMessage() {}

func (x *Greeting) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_greeter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Greeting.ProtoReflect.Descriptor instead.
func (*Greeting) Descriptor() ([]byte, []int) {
	return file_greeter_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *Greeting) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Hug struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Hug) Reset() {
	*x = Hug{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_greeter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hug) ProtoMessage() {}

func (x *Hug) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_greeter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hug.ProtoReflect.Descriptor instead.
func (*Hug) Descriptor() ([]byte, []int) {
	return file_greeter_greeter_proto_rawDescGZIP(), []int{1}
}

type CreateGreetingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateGreetingRequest) Reset() {
	*x = CreateGreetingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_greeter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGreetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGreetingRequest) ProtoMessage() {}

func (x *CreateGreetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_greeter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGreetingRequest.ProtoReflect.Descriptor instead.
func (*CreateGreetingRequest) Descriptor() ([]byte, []int) {
	return file_greeter_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGreetingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetGreetingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetGreetingRequest) Reset() {
	*x = GetGreetingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_greeter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGreetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreetingRequest) ProtoMessage() {}

func (x *GetGreetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_greeter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreetingRequest.ProtoReflect.Descriptor instead.
func (*GetGreetingRequest) Descriptor() ([]byte, []int) {
	return file_greeter_greeter_proto_rawDescGZIP(), []int{3}
}

func (x *GetGreetingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListGreetingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListGreetingsRequest) Reset() {
	*x = ListGreetingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_greeter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGreetingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGreetingsRequest) ProtoMessage() {}

func (x *ListGreetingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_greeter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGreetingsRequest.ProtoReflect.Descriptor instead.
func (*ListGreetingsRequest) Descriptor() ([]byte, []int) {
	return file_greeter_greeter_proto_rawDescGZIP(), []int{4}
}

type ListGreetingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greetings []*Greeting `protobuf:"bytes,1,rep,name=greetings,proto3" json:"greetings,omitempty"`
}

func (x *ListGreetingsResponse) Reset() {
	*x = ListGreetingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_greeter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGreetingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGreetingsResponse) ProtoMessage() {}

func (x *ListGreetingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_greeter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGreetingsResponse.ProtoReflect.Descriptor instead.
func (*ListGreetingsResponse) Descriptor() ([]byte, []int) {
	return file_greeter_greeter_proto_rawDescGZIP(), []int{5}
}

func (x *ListGreetingsResponse) GetGreetings() []*Greeting {
	if x != nil {
		return x.Greetings
	}
	return nil
}

type ListHugsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListHugsRequest) Reset() {
	*x = ListHugsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_greeter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHugsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHugsRequest) ProtoMessage() {}

func (x *ListHugsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_greeter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHugsRequest.ProtoReflect.Descriptor instead.
func (*ListHugsRequest) Descriptor() ([]byte, []int) {
	return file_greeter_greeter_proto_rawDescGZIP(), []int{6}
}

type ListHugsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hugs []*Hug `protobuf:"bytes,1,rep,name=hugs,proto3" json:"hugs,omitempty"`
}

func (x *ListHugsResponse) Reset() {
	*x = ListHugsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greeter_greeter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHugsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHugsResponse) ProtoMessage() {}

func (x *ListHugsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_greeter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHugsResponse.ProtoReflect.Descriptor instead.
func (*ListHugsResponse) Descriptor() ([]byte, []int) {
	return file_greeter_greeter_proto_rawDescGZIP(), []int{7}
}

func (x *ListHugsResponse) GetHugs() []*Hug {
	if x != nil {
		return x.Hugs
	}
	return nil
}

var File_greeter_greeter_proto protoreflect.FileDescriptor

var file_greeter_greeter_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72,
	0x22, 0x1e, 0x0a, 0x08, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x22, 0x05, 0x0a, 0x03, 0x48, 0x75, 0x67, 0x22, 0x2b, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x28, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x16,
	0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2f, 0x0a, 0x09, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x72, 0x65,
	0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x75, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x34, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x75, 0x67, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x68, 0x75, 0x67, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2e,
	0x48, 0x75, 0x67, 0x52, 0x04, 0x68, 0x75, 0x67, 0x73, 0x32, 0x9e, 0x02, 0x0a, 0x07, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
	0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65,
	0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65,
	0x72, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x3d, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72,
	0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x4e, 0x0a, 0x0d, 0x4c, 0x69, 0x73,
	0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1d, 0x2e, 0x67, 0x72, 0x65,
	0x65, 0x74, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x4c, 0x69, 0x73,
	0x74, 0x48, 0x75, 0x67, 0x73, 0x12, 0x18, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x75, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x75,
	0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3f, 0x0a, 0x0a, 0x67, 0x6c,
	0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x50, 0x01, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x48, 0x61, 0x79, 0x6f, 0x56, 0x61, 0x6e, 0x4c, 0x6f,
	0x6f, 0x6e, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x65, 0x72, 0x3b, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_greeter_greeter_proto_rawDescOnce sync.Once
	file_greeter_greeter_proto_rawDescData = file_greeter_greeter_proto_rawDesc
)

func file_greeter_greeter_proto_rawDescGZIP() []byte {
	file_greeter_greeter_proto_rawDescOnce.Do(func() {
		file_greeter_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(file_greeter_greeter_proto_rawDescData)
	})
	return file_greeter_greeter_proto_rawDescData
}

var file_greeter_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_greeter_greeter_proto_goTypes = []interface{}{
	(*Greeting)(nil),              // 0: greeter.Greeting
	(*Hug)(nil),                   // 1: greeter.Hug
	(*CreateGreetingRequest)(nil), // 2: greeter.CreateGreetingRequest
	(*GetGreetingRequest)(nil),    // 3: greeter.GetGreetingRequest
	(*ListGreetingsRequest)(nil),  // 4: greeter.ListGreetingsRequest
	(*ListGreetingsResponse)(nil), // 5: greeter.ListGreetingsResponse
	(*ListHugsRequest)(nil),       // 6: greeter.ListHugsRequest
	(*ListHugsResponse)(nil),      // 7: greeter.ListHugsResponse
}
var file_greeter_greeter_proto_depIdxs = []int32{
	0, // 0: greeter.ListGreetingsResponse.greetings:type_name -> greeter.Greeting
	1, // 1: greeter.ListHugsResponse.hugs:type_name -> greeter.Hug
	2, // 2: greeter.Greeter.CreateGreeting:input_type -> greeter.CreateGreetingRequest
	3, // 3: greeter.Greeter.GetGreeting:input_type -> greeter.GetGreetingRequest
	4, // 4: greeter.Greeter.ListGreetings:input_type -> greeter.ListGreetingsRequest
	6, // 5: greeter.Greeter.ListHugs:input_type -> greeter.ListHugsRequest
	0, // 6: greeter.Greeter.CreateGreeting:output_type -> greeter.Greeting
	0, // 7: greeter.Greeter.GetGreeting:output_type -> greeter.Greeting
	5, // 8: greeter.Greeter.ListGreetings:output_type -> greeter.ListGreetingsResponse
	7, // 9: greeter.Greeter.ListHugs:output_type -> greeter.ListHugsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_greeter_greeter_proto_init() }
func file_greeter_greeter_proto_init() {
	if File_greeter_greeter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_greeter_greeter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Greeting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_greeter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hug); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_greeter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGreetingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_greeter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGreetingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_greeter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGreetingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_greeter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGreetingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_greeter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHugsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greeter_greeter_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHugsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_greeter_greeter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greeter_greeter_proto_goTypes,
		DependencyIndexes: file_greeter_greeter_proto_depIdxs,
		MessageInfos:      file_greeter_greeter_proto_msgTypes,
	}.Build()
	File_greeter_greeter_proto = out.File
	file_greeter_greeter_proto_rawDesc = nil
	file_greeter_greeter_proto_goTypes = nil
	file_greeter_greeter_proto_depIdxs = nil
}
