// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cloudrungrpc/greeter.proto

package greeter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetGreetingRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGreetingRequest) Reset()         { *m = GetGreetingRequest{} }
func (m *GetGreetingRequest) String() string { return proto.CompactTextString(m) }
func (*GetGreetingRequest) ProtoMessage()    {}
func (*GetGreetingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd1af738d44a1a9c, []int{0}
}

func (m *GetGreetingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGreetingRequest.Unmarshal(m, b)
}
func (m *GetGreetingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGreetingRequest.Marshal(b, m, deterministic)
}
func (m *GetGreetingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGreetingRequest.Merge(m, src)
}
func (m *GetGreetingRequest) XXX_Size() int {
	return xxx_messageInfo_GetGreetingRequest.Size(m)
}
func (m *GetGreetingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGreetingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGreetingRequest proto.InternalMessageInfo

func (m *GetGreetingRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Greeting struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd1af738d44a1a9c, []int{1}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*GetGreetingRequest)(nil), "greeter.GetGreetingRequest")
	proto.RegisterType((*Greeting)(nil), "greeter.Greeting")
}

func init() { proto.RegisterFile("cloudrungrpc/greeter.proto", fileDescriptor_fd1af738d44a1a9c) }

var fileDescriptor_fd1af738d44a1a9c = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x3f, 0x4b, 0xc5, 0x40,
	0x10, 0xc4, 0x0d, 0x88, 0x4f, 0xd7, 0xca, 0xab, 0x24, 0x8a, 0x48, 0xaa, 0x57, 0xe5, 0x40, 0x4b,
	0x8b, 0x80, 0x4d, 0x44, 0x2c, 0x24, 0x85, 0x85, 0xdd, 0x25, 0x2e, 0xeb, 0x41, 0xb2, 0x1b, 0x2f,
	0x7b, 0xa0, 0xdf, 0x5e, 0xf2, 0xe7, 0x50, 0x78, 0xd5, 0xcd, 0xed, 0x6f, 0xd8, 0xd9, 0x81, 0xbc,
	0xeb, 0x25, 0x7e, 0x84, 0xc8, 0x14, 0xc6, 0xce, 0x52, 0x40, 0x54, 0x0c, 0xe5, 0x18, 0x44, 0xc5,
	0xec, 0xb6, 0x6f, 0x7e, 0x4d, 0x22, 0xd4, 0xa3, 0x75, 0xa3, 0xb7, 0x8e, 0x59, 0xd4, 0xa9, 0x17,
	0x9e, 0x56, 0x5b, 0xb1, 0x07, 0x53, 0xa3, 0xd6, 0xb3, 0xd7, 0x33, 0x35, 0xf8, 0x15, 0x71, 0x52,
	0x63, 0xe0, 0x98, 0xdd, 0x80, 0x97, 0xd9, 0x6d, 0xb6, 0x3f, 0x6b, 0x16, 0x5d, 0xdc, 0xc0, 0x69,
	0xb2, 0xcd, 0x5c, 0xf1, 0x5b, 0x13, 0x9f, 0xf5, 0xdd, 0x33, 0xec, 0xea, 0x35, 0xd2, 0x54, 0x70,
	0xfe, 0x6f, 0xa9, 0xb9, 0x2a, 0xd3, 0x69, 0x87, 0x51, 0xf9, 0xc5, 0x1f, 0xdc, 0x48, 0x71, 0xf4,
	0x58, 0x01, 0x50, 0x9f, 0xc0, 0x6b, 0xf6, 0x6e, 0xc9, 0xeb, 0x67, 0x6c, 0xcb, 0x4e, 0x06, 0xfb,
	0xe4, 0x7e, 0xe4, 0xcd, 0xf1, 0x8b, 0x08, 0x5b, 0x42, 0x5e, 0x6a, 0xa4, 0xee, 0x0f, 0xdb, 0xdb,
	0x9e, 0x2c, 0xe3, 0xfb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x17, 0x19, 0xe7, 0x70, 0x22, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	GetGreeting(ctx context.Context, in *GetGreetingRequest, opts ...grpc.CallOption) (*Greeting, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GetGreeting(ctx context.Context, in *GetGreetingRequest, opts ...grpc.CallOption) (*Greeting, error) {
	out := new(Greeting)
	err := c.cc.Invoke(ctx, "/greeter.Greeter/GetGreeting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	GetGreeting(context.Context, *GetGreetingRequest) (*Greeting, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_GetGreeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGreetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetGreeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greeter.Greeter/GetGreeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetGreeting(ctx, req.(*GetGreetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greeter.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGreeting",
			Handler:    _Greeter_GetGreeting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cloudrungrpc/greeter.proto",
}
